<a href="https://colab.research.google.com/github/Yashfa54/EDA-AICP-Internship/blob/main/EDA_Task_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Write a NumPy program to create an array of all even integers from 30 to 70.**

In [ ]:
import numpy as np

even_array = np.arange(30, 71, 2)
print("Array of even integers from 30 to 70:", even_array)


Array of even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.**

In [ ]:
import numpy as np

random_array = np.random.randn(15)
print("Random Array: ", random_array)
print("Array of 15 random numbers from a standard normal distribution:", random_array)

Random Array:  [ 1.38050972  0.51240531  1.08480218  1.5086104   0.25575136 -0.99796395
 -0.30615799 -0.67788308 -0.18148752 -0.90124981 -0.51946131  0.37004083
  1.00260268  0.5037085   0.01447303]
Array of 15 random numbers from a standard normal distribution: [ 1.38050972  0.51240531  1.08480218  1.5086104   0.25575136 -0.99796395
 -0.30615799 -0.67788308 -0.18148752 -0.90124981 -0.51946131  0.37004083
  1.00260268  0.5037085   0.01447303]


**How to compute the cross-product of two matrices in NumPy?**

In [ ]:
import numpy as np

# Define matrices
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# Compute cross-product
cross_product = np.cross(A, B)

print("Cross-product of A and B:", cross_product)

Cross-product of A and B: [-3  6 -3]


**How to compute the determinant of an array using NumPy?**

In [ ]:
import numpy as np

# Assuming you have an array 'arr'
n = 4
random_array = np.random.rand(n,n)

print("Random Array: ", random_array)
determinant = np.linalg.det(random_array)
print("Determinant of the array:", determinant)

Random Array:  [[0.26636009 0.1554965  0.67088117 0.36791014]
 [0.83664556 0.67996487 0.31046051 0.50152658]
 [0.65705683 0.76275532 0.97135526 0.43463876]
 [0.401677   0.80630925 0.99880482 0.14330753]]
Determinant of the array: 0.0015387668003786525


**How to create a 3x3x3 array with random values using NumPy?**

In [ ]:
import numpy as np

random_3d_array = np.random.rand(3, 3, 3)
print("Considered Array: ", random_3d_array)
print("3x3x3 array with random values:", random_3d_array)


Considered Array:  [[[0.02799794 0.53861436 0.87582279]
  [0.53195925 0.55552437 0.50636492]
  [0.96031953 0.05196552 0.98997246]]

 [[0.76042942 0.52411608 0.82133632]
  [0.86218081 0.67217894 0.8893658 ]
  [0.4302749  0.85371394 0.11542669]]

 [[0.63010555 0.51276257 0.23585922]
  [0.68318603 0.80457456 0.48168491]
  [0.63722548 0.09773716 0.34118165]]]
3x3x3 array with random values: [[[0.02799794 0.53861436 0.87582279]
  [0.53195925 0.55552437 0.50636492]
  [0.96031953 0.05196552 0.98997246]]

 [[0.76042942 0.52411608 0.82133632]
  [0.86218081 0.67217894 0.8893658 ]
  [0.4302749  0.85371394 0.11542669]]

 [[0.63010555 0.51276257 0.23585922]
  [0.68318603 0.80457456 0.48168491]
  [0.63722548 0.09773716 0.34118165]]]


**How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?**

In [ ]:
import numpy as np

random_5x5_array = np.random.rand(5, 5)
print("5x5 array with random values:")
print(random_5x5_array)
minimum_value = np.min(random_5x5_array)
maximum_value = np.max(random_5x5_array)
print("Minimum value:", minimum_value)
print("Maximum value:", maximum_value)


5x5 array with random values:
[[0.65777359 0.08743431 0.51874767 0.65160419 0.48905318]
 [0.04195614 0.43064272 0.2519988  0.21067709 0.38298988]
 [0.18580849 0.36561305 0.87456675 0.28300014 0.14224533]
 [0.88532415 0.14336496 0.93242338 0.657799   0.9664992 ]
 [0.78169291 0.29857466 0.91735614 0.61914814 0.62544366]]
Minimum value: 0.041956140563772504
Maximum value: 0.9664991978017162


**How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?**

In [ ]:
import numpy as np

# Assuming you have an array 'arr'
random_array = np.random.rand(3,3)

# Compute mean, standard deviation, and variance along the second axis
mean = np.mean(random_array, axis=1)
std_deviation = np.std(random_array, axis=1)
variance = np.var(random_array, axis=1)

print("Mean along the second axis:", mean)
print("Standard deviation along the second axis:", std_deviation)
print("Variance along the second axis:", variance)


Mean along the second axis: [0.56409702 0.59891369 0.68991022]
Standard deviation along the second axis: [0.30023506 0.36655078 0.24981637]
Variance along the second axis: [0.09014109 0.13435947 0.06240822]
